### ISSUE TITLE
How link minecraft-export with prometheus ?

### ISSUE THREAD

**Issue by Requaaw** [Joshi425/minecraft-exporter#16]
Hello,
I'm a beginner with prometheus and I sought of all forums but i really don't know how link prometheus and minecraft-exporter on them...

minecraft-export work
prometheus work

how link ?

please help me :(

[exporter.txt](https://github.com/Joshi425/minecraft-exporter/files/6563771/exporter.txt)

**Comment by LimesKey** [comment]
How did you do it?
