### ISSUE TITLE
Cannot add as a prometheus source in grafana due to comments

### ISSUE THREAD

**Issue by q23407u892f** [Joshi425/minecraft-exporter#26]
When trying to add this as a data source to grafana, it barfs due to the lines starting with comments
![image](https://user-images.githubusercontent.com/87550097/184414977-32ef0d2b-259d-43ed-8aa8-9cc08ce8d55d.png)

```
Error reading Prometheus: bad_response: readObjectStart: expect { or n, but found #, error found in #1 byte of ...|# HELP pyth|..., bigger context ...|# HELP python_gc_objects_collected_total Objects co|...
```

**Comment by Joshi425** [comment]
This is only a prometheus Exporter, you setup Prometheus to scrape the Exporter and add Prometheus to Grafana.

Take a Look here: https://prometheus.io/
