### ISSUE TITLE
No server metrics - Error mcrcon.MCRconException: Incorrect padding

### ISSUE THREAD

**Issue by LimesKey** [Joshi425/minecraft-exporter#37]
I'm using Purpur 1.20.1 with Application Management Panel and I have enabled the RCON port and everything configured correctly I believe. I just installed the docker a few minutes ago and set everything up, but I am getting no metrics from either the world and RCON.

I receive the error message `mcrcon.MCRconException: Incorrect padding` (followed by at what line) after about 5 minutes of the docker container running. The full log is here. [minecraft-exporter-log.txt](https://github.com/Joshi425/minecraft-exporter/files/11998383/minecraft-exporter-log.txt). The full metrics it gives me at the IP `http://192.168.1.100:5042/metrics` are here [exporter-metrics.txt](https://github.com/Joshi425/minecraft-exporter/files/11998388/exporter-metrics.txt). Not really sure what else to do to make it work.

My docker container config look like this:
```
docker run
  -d
  --name='minecraft-exporter'
  --net='dockernet'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Dragon"
  -e HOST_CONTAINERNAME="minecraft-exporter"
  -e 'RCON_HOST'='192.168.1.100'
  -e 'RCON_PORT'='9940'
  -e 'RCON_PASSWORD'='Password'
  -e 'PAPER_SERVER'='True'
  -e 'FORGE_SERVER'='False'
  -e 'DYNMAP_ENABLED'='False'
  -l net.unraid.docker.managed=dockerman
  -p '5042:8000/tcp'
  -v '/mnt/user/appdata/amp/instances/MineLime01/Minecraft/world/':'/world':'ro' 'joshi425/minecraft-exporter' 
```
My Prometheus config looks like this:
```
  - job_name: Minecraft Export
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.100:5042']
 ```

**Comment by heathcliff26** [comment]
Not eure if you still habe the problem @LimesKey, but looks to me like the Problem are the apostrophes. It tries to call `'192.168.1.100'`, but should be calling `192.168.1.100`. Same for the other enviroment variables. Just write the values as is.

**Comment by LimesKey** [comment]
@heathcliff26 I never added any apostrophes to the environment variables, I wrote the IP exactly as is without any extra characters. It shows an apostrophe in the docker config to show it's a string.

**Comment by heathcliff26** [comment]
Hmm, maybe try with an enviroment file instead?
```
#!/bin/env bash
# shellcheck disable=all

FORGE_SERVER=False
PAPER_SERVER=True
DYNMAP_ENABLED=False
RCON_HOST=192.168.1.100
RCON_PORT=9940
RCON_PASSWORD=Password
```
and then
```
docker run -d 
        --env-file minecraft-exporter.env \
        --name=minecraft-exporter \
        --net=dockernet
        -p 5042:8000
        -v /mnt/user/appdata/amp/instances/MineLime01/Minecraft/world:/world:ro
        joshi425/minecraft-exporter:latest
```
If that doesn't help, you can try `ghcr.io/heathcliff26/minecraft-exporter:latest` instead, i think i remember i tried to improve stability at one point with RCON. Mainly because this project does not seem to be maintained anyomre.

**Comment by LimesKey** [comment]
It's difficult to use an environment file or a custom docker run command on the operating system I'm using. It's ok, I've given up and don't really care anymore. Thanks for your help though @heathcliff26.
