### ISSUE TITLE
First username used

### ISSUE THREAD

**Issue by NicholasFeldman** [Joshi425/minecraft-exporter#5]
For players who have had name changes, it it not reflected. Instead, the first username is always used

Example of name changes: https://api.mojang.com/user/profiles/6e8e4f6fa4144f13962c6d914363788a/names

https://github.com/Joshi425/minecraft-exporter/blob/e1203644ff4b47f0748ed63e5efb1dfd201a934d/minecraft_exporter.py#L31-L33

**Comment by Joshi425** [comment]
Yeah thats correct, we can use -1, to always use the latest name. But if someone changes his name the exporter had to be restarted to flush the username cache. the only thing I can think of right now is to use the latest username and renew the usernames every 30 minutes or so.

I will think about this.

**Comment by Joshi425** [comment]
I've updated the exporter, it now flushes the username cache once a day + always uses the last username. Please make sure to `docker pull joshi425/minecraft_exporter` to update the exporter.
