### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Gensokian** [Joshi425/minecraft-exporter#7]
Hello!
I've been running a little Minecraft server on a Pi 4 and encountered this "Exec format error".
After a bit of googling around, I found out, that it might be because the docker image was compiled for an intel 32x/64x kernel (Whilst the Pi is running an ARM kernel.) (Source: https://github.com/edgedb/edgedb-docker/issues/2)

Can you help me with that issue somehow?

Also, I wondered if it is possible to somehow run that container externally on another system, by using a network share or something.

Thanks in advance!

**Comment by Joshi425** [comment]
Hi there :) 
yeah this docker container is based on `python:3` but if you build it on `arm32v7/python:3` it should work as well. 
I'm currenty unable to pull this image:
```
$docker pull arm32v7/python:3
Pulling repository docker.io/arm32v7/python
Could not reach any registry endpoint
```
but maybe you can make it work. just clone the repo and adjust the "From" in the Dockerfile. Then run docker build . -t minecraft_exporter

after that it should be able to start. 

The exporter should work over a network share, like sshfs or ftp mounted via fuse but I have no experience with that. You can give it a Try. technically it should work
